import React from 'react';

export default function FeatureGrid() {
  const features = [
    {
      title: "AST-Aware Chunking",
      description: "Code is parsed semantically using tree-sitter. We never split functions mid-body, ensuring complete context.",
    },
    {
      title: "Hybrid Retrieval",
      description: "Combines BM25 keyword search with dense embeddings, followed by cross-encoder reranking for maximum precision.",
    },
    {
      title: "Cited Answers",
      description: "Every answer generated by the LLM includes exact file:line references, so you always know where the information came from.",
    }
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-5xl">
      {features.map((feature, idx) => (
        <div key={idx} className="glass-panel border border-green-500/20 rounded-xl p-6 flex flex-col items-start text-left shadow-lg">
          <h3 className="text-xl font-semibold text-zinc-100 mb-3">{feature.title}</h3>
          <p className="text-green-100/60 text-sm leading-relaxed">{feature.description}</p>
        </div>
      ))}
    </div>
  );
}
